// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  accountGetAccountConfig,
  cortexActivityEventsTrackActivityEvent,
  cortexAgentsGetAgent,
  cortexAgentsListCategories,
  cortexAgentsRunAgent,
  cortexWorkflowsCancelWorkflow,
  cortexWorkflowsGetWorkflowStatus,
  cortexWorkflowsListWorkflows,
  cortexWorkflowsStreamWorkflowEvents,
  getAdminConstants,
  internalListTargets,
  internalSubmitFeedback,
  type Options,
  styleAgentGetStyleAgentConfig,
  styleAgentListStyleAgentContentProfiles,
  styleAgentListStyleAgentTargets,
  terminologyCreateDomain,
  terminologyDeleteDomain,
  terminologyGetDomain,
  terminologyListDomains,
  terminologyUpdateDomain,
} from "../sdk.gen";
import type {
  AccountGetAccountConfigData,
  AccountGetAccountConfigError,
  AccountGetAccountConfigResponse,
  CortexActivityEventsTrackActivityEventData,
  CortexActivityEventsTrackActivityEventError,
  CortexActivityEventsTrackActivityEventResponse,
  CortexAgentsGetAgentData,
  CortexAgentsGetAgentError,
  CortexAgentsGetAgentResponse,
  CortexAgentsListCategoriesData,
  CortexAgentsListCategoriesError,
  CortexAgentsListCategoriesResponse,
  CortexAgentsRunAgentData,
  CortexAgentsRunAgentError,
  CortexAgentsRunAgentResponse,
  CortexWorkflowsCancelWorkflowData,
  CortexWorkflowsCancelWorkflowError,
  CortexWorkflowsCancelWorkflowResponse,
  CortexWorkflowsGetWorkflowStatusData,
  CortexWorkflowsGetWorkflowStatusError,
  CortexWorkflowsGetWorkflowStatusResponse,
  CortexWorkflowsListWorkflowsData,
  CortexWorkflowsListWorkflowsError,
  CortexWorkflowsListWorkflowsResponse,
  CortexWorkflowsStreamWorkflowEventsData,
  CortexWorkflowsStreamWorkflowEventsError,
  GetAdminConstantsData,
  GetAdminConstantsError,
  GetAdminConstantsResponse,
  InternalListTargetsData,
  InternalListTargetsError,
  InternalListTargetsResponse,
  InternalSubmitFeedbackData,
  InternalSubmitFeedbackError,
  InternalSubmitFeedbackResponse,
  StyleAgentGetStyleAgentConfigData,
  StyleAgentGetStyleAgentConfigError,
  StyleAgentGetStyleAgentConfigResponse,
  StyleAgentListStyleAgentContentProfilesData,
  StyleAgentListStyleAgentContentProfilesError,
  StyleAgentListStyleAgentContentProfilesResponse,
  StyleAgentListStyleAgentTargetsData,
  StyleAgentListStyleAgentTargetsError,
  StyleAgentListStyleAgentTargetsResponse,
  TerminologyCreateDomainData,
  TerminologyCreateDomainError,
  TerminologyCreateDomainResponse,
  TerminologyDeleteDomainData,
  TerminologyDeleteDomainError,
  TerminologyDeleteDomainResponse,
  TerminologyGetDomainData,
  TerminologyGetDomainError,
  TerminologyGetDomainResponse,
  TerminologyListDomainsData,
  TerminologyListDomainsError,
  TerminologyListDomainsResponse,
  TerminologyUpdateDomainData,
  TerminologyUpdateDomainError,
  TerminologyUpdateDomainResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getAdminConstantsQueryKey = (options?: Options<GetAdminConstantsData>) =>
  createQueryKey("getAdminConstants", options);

/**
 * Get Admin Constants
 */
export const getAdminConstantsOptions = (options?: Options<GetAdminConstantsData>) =>
  queryOptions<
    GetAdminConstantsResponse,
    GetAdminConstantsError,
    GetAdminConstantsResponse,
    ReturnType<typeof getAdminConstantsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminConstants({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAdminConstantsQueryKey(options),
  });

export const terminologyListDomainsQueryKey = (options?: Options<TerminologyListDomainsData>) =>
  createQueryKey("terminologyListDomains", options);

/**
 * List Domains
 */
export const terminologyListDomainsOptions = (options?: Options<TerminologyListDomainsData>) =>
  queryOptions<
    TerminologyListDomainsResponse,
    TerminologyListDomainsError,
    TerminologyListDomainsResponse,
    ReturnType<typeof terminologyListDomainsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await terminologyListDomains({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: terminologyListDomainsQueryKey(options),
  });

/**
 * Create Domain
 */
export const terminologyCreateDomainMutation = (
  options?: Partial<Options<TerminologyCreateDomainData>>,
): UseMutationOptions<
  TerminologyCreateDomainResponse,
  TerminologyCreateDomainError,
  Options<TerminologyCreateDomainData>
> => {
  const mutationOptions: UseMutationOptions<
    TerminologyCreateDomainResponse,
    TerminologyCreateDomainError,
    Options<TerminologyCreateDomainData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await terminologyCreateDomain({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Domain
 */
export const terminologyDeleteDomainMutation = (
  options?: Partial<Options<TerminologyDeleteDomainData>>,
): UseMutationOptions<
  TerminologyDeleteDomainResponse,
  TerminologyDeleteDomainError,
  Options<TerminologyDeleteDomainData>
> => {
  const mutationOptions: UseMutationOptions<
    TerminologyDeleteDomainResponse,
    TerminologyDeleteDomainError,
    Options<TerminologyDeleteDomainData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await terminologyDeleteDomain({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const terminologyGetDomainQueryKey = (options: Options<TerminologyGetDomainData>) =>
  createQueryKey("terminologyGetDomain", options);

/**
 * Get Domain
 */
export const terminologyGetDomainOptions = (options: Options<TerminologyGetDomainData>) =>
  queryOptions<
    TerminologyGetDomainResponse,
    TerminologyGetDomainError,
    TerminologyGetDomainResponse,
    ReturnType<typeof terminologyGetDomainQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await terminologyGetDomain({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: terminologyGetDomainQueryKey(options),
  });

/**
 * Update Domain
 */
export const terminologyUpdateDomainMutation = (
  options?: Partial<Options<TerminologyUpdateDomainData>>,
): UseMutationOptions<
  TerminologyUpdateDomainResponse,
  TerminologyUpdateDomainError,
  Options<TerminologyUpdateDomainData>
> => {
  const mutationOptions: UseMutationOptions<
    TerminologyUpdateDomainResponse,
    TerminologyUpdateDomainError,
    Options<TerminologyUpdateDomainData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await terminologyUpdateDomain({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Submit Feedback
 */
export const internalSubmitFeedbackMutation = (
  options?: Partial<Options<InternalSubmitFeedbackData>>,
): UseMutationOptions<
  InternalSubmitFeedbackResponse,
  InternalSubmitFeedbackError,
  Options<InternalSubmitFeedbackData>
> => {
  const mutationOptions: UseMutationOptions<
    InternalSubmitFeedbackResponse,
    InternalSubmitFeedbackError,
    Options<InternalSubmitFeedbackData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await internalSubmitFeedback({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const internalListTargetsQueryKey = (options?: Options<InternalListTargetsData>) =>
  createQueryKey("internalListTargets", options);

/**
 * List Targets
 */
export const internalListTargetsOptions = (options?: Options<InternalListTargetsData>) =>
  queryOptions<
    InternalListTargetsResponse,
    InternalListTargetsError,
    InternalListTargetsResponse,
    ReturnType<typeof internalListTargetsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await internalListTargets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: internalListTargetsQueryKey(options),
  });

/**
 * Track Activity Event
 *
 * Track a user action on an agent issue in the Chrome extension.
 *
 * Emits a single combined event (API metadata + activity data) to Kinesis.
 * Returns 204 immediately — event emission is non-blocking.
 */
export const cortexActivityEventsTrackActivityEventMutation = (
  options?: Partial<Options<CortexActivityEventsTrackActivityEventData>>,
): UseMutationOptions<
  CortexActivityEventsTrackActivityEventResponse,
  CortexActivityEventsTrackActivityEventError,
  Options<CortexActivityEventsTrackActivityEventData>
> => {
  const mutationOptions: UseMutationOptions<
    CortexActivityEventsTrackActivityEventResponse,
    CortexActivityEventsTrackActivityEventError,
    Options<CortexActivityEventsTrackActivityEventData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cortexActivityEventsTrackActivityEvent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const cortexWorkflowsListWorkflowsQueryKey = (
  options?: Options<CortexWorkflowsListWorkflowsData>,
) => createQueryKey("cortexWorkflowsListWorkflows", options);

/**
 * List Workflows
 *
 * List agent workflow executions with optional filters and cursor-based pagination.
 */
export const cortexWorkflowsListWorkflowsOptions = (
  options?: Options<CortexWorkflowsListWorkflowsData>,
) =>
  queryOptions<
    CortexWorkflowsListWorkflowsResponse,
    CortexWorkflowsListWorkflowsError,
    CortexWorkflowsListWorkflowsResponse,
    ReturnType<typeof cortexWorkflowsListWorkflowsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cortexWorkflowsListWorkflows({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: cortexWorkflowsListWorkflowsQueryKey(options),
  });

/**
 * Cancel Workflow
 *
 * Cancel a running workflow.
 */
export const cortexWorkflowsCancelWorkflowMutation = (
  options?: Partial<Options<CortexWorkflowsCancelWorkflowData>>,
): UseMutationOptions<
  CortexWorkflowsCancelWorkflowResponse,
  CortexWorkflowsCancelWorkflowError,
  Options<CortexWorkflowsCancelWorkflowData>
> => {
  const mutationOptions: UseMutationOptions<
    CortexWorkflowsCancelWorkflowResponse,
    CortexWorkflowsCancelWorkflowError,
    Options<CortexWorkflowsCancelWorkflowData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cortexWorkflowsCancelWorkflow({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const cortexWorkflowsGetWorkflowStatusQueryKey = (
  options: Options<CortexWorkflowsGetWorkflowStatusData>,
) => createQueryKey("cortexWorkflowsGetWorkflowStatus", options);

/**
 * Get Workflow Status
 *
 * Get workflow status and result.
 */
export const cortexWorkflowsGetWorkflowStatusOptions = (
  options: Options<CortexWorkflowsGetWorkflowStatusData>,
) =>
  queryOptions<
    CortexWorkflowsGetWorkflowStatusResponse,
    CortexWorkflowsGetWorkflowStatusError,
    CortexWorkflowsGetWorkflowStatusResponse,
    ReturnType<typeof cortexWorkflowsGetWorkflowStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cortexWorkflowsGetWorkflowStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: cortexWorkflowsGetWorkflowStatusQueryKey(options),
  });

export const cortexWorkflowsStreamWorkflowEventsQueryKey = (
  options: Options<CortexWorkflowsStreamWorkflowEventsData>,
) => createQueryKey("cortexWorkflowsStreamWorkflowEvents", options);

/**
 * Stream Workflow Events
 *
 * Stream workflow execution events via Server-Sent Events (SSE).
 */
export const cortexWorkflowsStreamWorkflowEventsOptions = (
  options: Options<CortexWorkflowsStreamWorkflowEventsData>,
) =>
  queryOptions<
    unknown,
    CortexWorkflowsStreamWorkflowEventsError,
    unknown,
    ReturnType<typeof cortexWorkflowsStreamWorkflowEventsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cortexWorkflowsStreamWorkflowEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: cortexWorkflowsStreamWorkflowEventsQueryKey(options),
  });

export const cortexAgentsListCategoriesQueryKey = (
  options?: Options<CortexAgentsListCategoriesData>,
) => createQueryKey("cortexAgentsListCategories", options);

/**
 * List Categories
 *
 * List all available agent categories.
 */
export const cortexAgentsListCategoriesOptions = (
  options?: Options<CortexAgentsListCategoriesData>,
) =>
  queryOptions<
    CortexAgentsListCategoriesResponse,
    CortexAgentsListCategoriesError,
    CortexAgentsListCategoriesResponse,
    ReturnType<typeof cortexAgentsListCategoriesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cortexAgentsListCategories({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: cortexAgentsListCategoriesQueryKey(options),
  });

export const cortexAgentsGetAgentQueryKey = (options: Options<CortexAgentsGetAgentData>) =>
  createQueryKey("cortexAgentsGetAgent", options);

/**
 * Get Agent
 *
 * Get agent metadata.
 */
export const cortexAgentsGetAgentOptions = (options: Options<CortexAgentsGetAgentData>) =>
  queryOptions<
    CortexAgentsGetAgentResponse,
    CortexAgentsGetAgentError,
    CortexAgentsGetAgentResponse,
    ReturnType<typeof cortexAgentsGetAgentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await cortexAgentsGetAgent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: cortexAgentsGetAgentQueryKey(options),
  });

/**
 * Run Agent
 *
 * Run an agent.
 *
 * Use `wait=true` to block until the workflow completes (201 Created).
 * Default (`wait=false`) returns immediately with 202 Accepted.
 */
export const cortexAgentsRunAgentMutation = (
  options?: Partial<Options<CortexAgentsRunAgentData>>,
): UseMutationOptions<
  CortexAgentsRunAgentResponse,
  CortexAgentsRunAgentError,
  Options<CortexAgentsRunAgentData>
> => {
  const mutationOptions: UseMutationOptions<
    CortexAgentsRunAgentResponse,
    CortexAgentsRunAgentError,
    Options<CortexAgentsRunAgentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cortexAgentsRunAgent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const accountGetAccountConfigQueryKey = (options?: Options<AccountGetAccountConfigData>) =>
  createQueryKey("accountGetAccountConfig", options);

/**
 * Get Account Config
 *
 * Return the org-level config slice that drives integration behaviour.
 *
 * Auth: JWT or API key. The org is identified by the credential — no org
 * id is taken from the request, so API-key consumers don't need to know
 * which org they're tied to.
 */
export const accountGetAccountConfigOptions = (options?: Options<AccountGetAccountConfigData>) =>
  queryOptions<
    AccountGetAccountConfigResponse,
    AccountGetAccountConfigError,
    AccountGetAccountConfigResponse,
    ReturnType<typeof accountGetAccountConfigQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await accountGetAccountConfig({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: accountGetAccountConfigQueryKey(options),
  });

export const styleAgentGetStyleAgentConfigQueryKey = (
  options?: Options<StyleAgentGetStyleAgentConfigData>,
) => createQueryKey("styleAgentGetStyleAgentConfig", options);

/**
 * Get Style Agent Config
 */
export const styleAgentGetStyleAgentConfigOptions = (
  options?: Options<StyleAgentGetStyleAgentConfigData>,
) =>
  queryOptions<
    StyleAgentGetStyleAgentConfigResponse,
    StyleAgentGetStyleAgentConfigError,
    StyleAgentGetStyleAgentConfigResponse,
    ReturnType<typeof styleAgentGetStyleAgentConfigQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await styleAgentGetStyleAgentConfig({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: styleAgentGetStyleAgentConfigQueryKey(options),
  });

export const styleAgentListStyleAgentTargetsQueryKey = (
  options?: Options<StyleAgentListStyleAgentTargetsData>,
) => createQueryKey("styleAgentListStyleAgentTargets", options);

/**
 * List Style Agent Targets
 */
export const styleAgentListStyleAgentTargetsOptions = (
  options?: Options<StyleAgentListStyleAgentTargetsData>,
) =>
  queryOptions<
    StyleAgentListStyleAgentTargetsResponse,
    StyleAgentListStyleAgentTargetsError,
    StyleAgentListStyleAgentTargetsResponse,
    ReturnType<typeof styleAgentListStyleAgentTargetsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await styleAgentListStyleAgentTargets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: styleAgentListStyleAgentTargetsQueryKey(options),
  });

export const styleAgentListStyleAgentContentProfilesQueryKey = (
  options?: Options<StyleAgentListStyleAgentContentProfilesData>,
) => createQueryKey("styleAgentListStyleAgentContentProfiles", options);

/**
 * List Style Agent Content Profiles
 */
export const styleAgentListStyleAgentContentProfilesOptions = (
  options?: Options<StyleAgentListStyleAgentContentProfilesData>,
) =>
  queryOptions<
    StyleAgentListStyleAgentContentProfilesResponse,
    StyleAgentListStyleAgentContentProfilesError,
    StyleAgentListStyleAgentContentProfilesResponse,
    ReturnType<typeof styleAgentListStyleAgentContentProfilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await styleAgentListStyleAgentContentProfiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: styleAgentListStyleAgentContentProfilesQueryKey(options),
  });
