// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AccountGetAccountConfigData,
  AccountGetAccountConfigErrors,
  AccountGetAccountConfigResponses,
  AccountGetAccountData,
  AccountGetAccountErrors,
  AccountGetAccountResponses,
  AuthenticationGetUserOrganizationsData,
  AuthenticationGetUserOrganizationsErrors,
  AuthenticationGetUserOrganizationsResponses,
  CortexActivityEventsTrackActivityEventData,
  CortexActivityEventsTrackActivityEventErrors,
  CortexActivityEventsTrackActivityEventResponses,
  CortexAgentsGetAgentData,
  CortexAgentsGetAgentErrors,
  CortexAgentsGetAgentResponses,
  CortexAgentsListCategoriesData,
  CortexAgentsListCategoriesErrors,
  CortexAgentsListCategoriesResponses,
  CortexAgentsRunAgentData,
  CortexAgentsRunAgentErrors,
  CortexAgentsRunAgentResponses,
  CortexWorkflowsCancelWorkflowData,
  CortexWorkflowsCancelWorkflowErrors,
  CortexWorkflowsCancelWorkflowResponses,
  CortexWorkflowsGetWorkflowStatusData,
  CortexWorkflowsGetWorkflowStatusErrors,
  CortexWorkflowsGetWorkflowStatusResponses,
  CortexWorkflowsListWorkflowsData,
  CortexWorkflowsListWorkflowsErrors,
  CortexWorkflowsListWorkflowsResponses,
  CortexWorkflowsStreamWorkflowEventsData,
  CortexWorkflowsStreamWorkflowEventsErrors,
  CortexWorkflowsStreamWorkflowEventsResponses,
  GetAdminConstantsData,
  GetAdminConstantsErrors,
  GetAdminConstantsResponses,
  StyleAgentListStyleGuidesData,
  StyleAgentListStyleGuidesErrors,
  StyleAgentListStyleGuidesResponses,
  TerminologyCreateDomainData,
  TerminologyCreateDomainErrors,
  TerminologyCreateDomainResponses,
  TerminologyDeleteDomainData,
  TerminologyDeleteDomainErrors,
  TerminologyDeleteDomainResponses,
  TerminologyGetDomainData,
  TerminologyGetDomainErrors,
  TerminologyGetDomainResponses,
  TerminologyListDomainsData,
  TerminologyListDomainsErrors,
  TerminologyListDomainsResponses,
  TerminologyUpdateDomainData,
  TerminologyUpdateDomainErrors,
  TerminologyUpdateDomainResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Admin Constants
 *
 * @deprecated
 */
export const getAdminConstants = <ThrowOnError extends boolean = false>(
  options?: Options<GetAdminConstantsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAdminConstantsResponses,
    GetAdminConstantsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/internal/constants",
    ...options,
  });

/**
 * List Domains
 *
 * @deprecated
 */
export const terminologyListDomains = <ThrowOnError extends boolean = false>(
  options?: Options<TerminologyListDomainsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TerminologyListDomainsResponses,
    TerminologyListDomainsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/terminology/domains",
    ...options,
  });

/**
 * Create Domain
 *
 * @deprecated
 */
export const terminologyCreateDomain = <ThrowOnError extends boolean = false>(
  options: Options<TerminologyCreateDomainData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TerminologyCreateDomainResponses,
    TerminologyCreateDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/terminology/domains",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Domain
 *
 * @deprecated
 */
export const terminologyDeleteDomain = <ThrowOnError extends boolean = false>(
  options: Options<TerminologyDeleteDomainData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TerminologyDeleteDomainResponses,
    TerminologyDeleteDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/terminology/domains/{domain_id}",
    ...options,
  });

/**
 * Get Domain
 *
 * @deprecated
 */
export const terminologyGetDomain = <ThrowOnError extends boolean = false>(
  options: Options<TerminologyGetDomainData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TerminologyGetDomainResponses,
    TerminologyGetDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/terminology/domains/{domain_id}",
    ...options,
  });

/**
 * Update Domain
 *
 * @deprecated
 */
export const terminologyUpdateDomain = <ThrowOnError extends boolean = false>(
  options: Options<TerminologyUpdateDomainData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    TerminologyUpdateDomainResponses,
    TerminologyUpdateDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/terminology/domains/{domain_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Style Guides
 *
 * List the style guides available to your organization.
 */
export const styleAgentListStyleGuides = <ThrowOnError extends boolean = false>(
  options?: Options<StyleAgentListStyleGuidesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    StyleAgentListStyleGuidesResponses,
    StyleAgentListStyleGuidesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/style-agent/style-guides",
    ...options,
  });

/**
 * Get Account
 *
 * Get account information for the authenticated user's organization
 */
export const accountGetAccount = <ThrowOnError extends boolean = false>(
  options?: Options<AccountGetAccountData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AccountGetAccountResponses,
    AccountGetAccountErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/account",
    ...options,
  });

/**
 * Get User Organizations
 *
 * Get organizations that the authenticated user belongs to.
 */
export const authenticationGetUserOrganizations = <ThrowOnError extends boolean = false>(
  options?: Options<AuthenticationGetUserOrganizationsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AuthenticationGetUserOrganizationsResponses,
    AuthenticationGetUserOrganizationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/organizations",
    ...options,
  });

/**
 * Track Activity Event
 *
 * Track a user action on an agent issue in the Chrome extension.
 *
 * Emits a single combined event (API metadata + activity data) to Kinesis.
 * Returns 204 immediately — event emission is non-blocking.
 */
export const cortexActivityEventsTrackActivityEvent = <ThrowOnError extends boolean = false>(
  options: Options<CortexActivityEventsTrackActivityEventData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CortexActivityEventsTrackActivityEventResponses,
    CortexActivityEventsTrackActivityEventErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/activity-events",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Workflows
 *
 * List agent workflow executions with optional filters and cursor-based pagination.
 */
export const cortexWorkflowsListWorkflows = <ThrowOnError extends boolean = false>(
  options?: Options<CortexWorkflowsListWorkflowsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CortexWorkflowsListWorkflowsResponses,
    CortexWorkflowsListWorkflowsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/workflows",
    ...options,
  });

/**
 * Cancel Workflow
 *
 * Cancel a running workflow.
 */
export const cortexWorkflowsCancelWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<CortexWorkflowsCancelWorkflowData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CortexWorkflowsCancelWorkflowResponses,
    CortexWorkflowsCancelWorkflowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/workflows/{workflow_id}",
    ...options,
  });

/**
 * Get Workflow Status
 *
 * Get workflow status and result.
 */
export const cortexWorkflowsGetWorkflowStatus = <ThrowOnError extends boolean = false>(
  options: Options<CortexWorkflowsGetWorkflowStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CortexWorkflowsGetWorkflowStatusResponses,
    CortexWorkflowsGetWorkflowStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/workflows/{workflow_id}",
    ...options,
  });

/**
 * Stream Workflow Events
 *
 * Stream workflow execution events via Server-Sent Events (SSE).
 */
export const cortexWorkflowsStreamWorkflowEvents = <ThrowOnError extends boolean = false>(
  options: Options<CortexWorkflowsStreamWorkflowEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CortexWorkflowsStreamWorkflowEventsResponses,
    CortexWorkflowsStreamWorkflowEventsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/workflows/{workflow_id}/stream",
    ...options,
  });

/**
 * List Categories
 *
 * List all available agent categories.
 */
export const cortexAgentsListCategories = <ThrowOnError extends boolean = false>(
  options?: Options<CortexAgentsListCategoriesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CortexAgentsListCategoriesResponses,
    CortexAgentsListCategoriesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/categories",
    ...options,
  });

/**
 * Get Agent
 *
 * Get agent metadata.
 */
export const cortexAgentsGetAgent = <ThrowOnError extends boolean = false>(
  options: Options<CortexAgentsGetAgentData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CortexAgentsGetAgentResponses,
    CortexAgentsGetAgentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/{agent_id}",
    ...options,
  });

/**
 * Run Agent
 *
 * Run an agent.
 *
 * Use `wait=true` to block until the workflow completes (201 Created).
 * Default (`wait=false`) returns immediately with 202 Accepted.
 */
export const cortexAgentsRunAgent = <ThrowOnError extends boolean = false>(
  options: Options<CortexAgentsRunAgentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CortexAgentsRunAgentResponses,
    CortexAgentsRunAgentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/agents/{agent_id}/run",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Account Config
 *
 * Return the org-level config slice that drives integration behaviour.
 *
 * Auth: JWT or API key. The org is identified by the credential — no org
 * id is taken from the request, so API-key consumers don't need to know
 * which org they're tied to.
 */
export const accountGetAccountConfig = <ThrowOnError extends boolean = false>(
  options?: Options<AccountGetAccountConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AccountGetAccountConfigResponses,
    AccountGetAccountConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/account/config",
    ...options,
  });
