// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | "https://api.markup.ai"
    | "https://api.stg.markup.ai"
    | "https://api.dev.markup.ai"
    | "http://localhost:8000"
    | (string & {});
};

/**
 * WorkflowStatus
 *
 * Status of a workflow execution.
 */
export enum HeliosSharedCortexModelsResponseWorkflowStatus {
  RUNNING = "running",
  COMPLETED = "completed",
  FAILED = "failed",
  TIMED_OUT = "timed_out",
  CANCELLED = "cancelled",
}

/**
 * StyleAgentMode
 */
export enum StyleAgentMode {
  DISABLED = "disabled",
  ENABLED = "enabled",
  ENABLED_TERMINOLOGY = "enabled_terminology",
}

/**
 * Organization
 */
export type HeliosOneApiModulesAuthMainOrganization = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Picture
   */
  picture: string;
};

/**
 * WorkflowStatusResponse
 *
 * Status response for a workflow.
 */
export type WorkflowStatusResponse = {
  /**
   * Workflow Id
   *
   * Workflow ID
   */
  workflow_id: string;
  /**
   * Agent Id
   *
   * Agent that ran this workflow
   */
  agent_id?: string;
  /**
   * Document Ref
   *
   * Caller-provided document identifier.
   */
  document_ref?: string | null;
  /**
   * Current status
   */
  status: HeliosSharedCortexModelsResponseWorkflowStatus;
  /**
   * Result
   *
   * Result (if completed)
   */
  result?: {
    [key: string]: unknown;
  } | null;
  /**
   * Started At
   *
   * Start time
   */
  started_at: string;
  /**
   * Completed At
   *
   * Workflow completion time
   */
  completed_at?: string | null;
};

/**
 * WorkflowListResponse
 *
 * Paginated list of workflow executions.
 */
export type WorkflowListResponse = {
  /**
   * Workflows
   *
   * Workflow executions
   */
  workflows: Array<WorkflowStatusResponse>;
  /**
   * Pagination metadata
   */
  pagination: PaginationInfo;
};

/**
 * PaginationInfo
 *
 * Cursor-based pagination metadata.
 */
export type PaginationInfo = {
  /**
   * Next Cursor
   *
   * Opaque cursor for fetching the next page
   */
  next_cursor?: string | null;
  /**
   * Has More
   *
   * Whether more results are available
   */
  has_more: boolean;
};

/**
 * WorkflowCancelResponse
 *
 * Response from cancelling a workflow.
 */
export type WorkflowCancelResponse = {
  /**
   * Workflow Id
   *
   * Workflow ID
   */
  workflow_id: string;
  /**
   * Cancelled At
   *
   * Timestamp when cancellation was requested
   */
  cancelled_at: string;
};

/**
 * ValidationErrorResponse
 */
export type ValidationErrorResponse = {
  /**
   * Detail
   *
   * A description of the error that occurred.
   */
  detail: string;
  /**
   * Status
   *
   * The HTTP status code generated by the server for this issue
   */
  status: number;
  /**
   * Request Id
   *
   * A unique ID associated with the HTTP request.
   */
  request_id: string;
  /**
   * Errors
   *
   * Detailed field-specific errors
   */
  errors?: Array<ValidationErrorItem>;
};

/**
 * ValidationErrorItem
 */
export type ValidationErrorItem = {
  /**
   * Type
   *
   * The type of error that occurred.
   */
  type: string;
  /**
   * Loc
   *
   * The location of the error in the request.
   */
  loc: Array<unknown>;
  /**
   * Msg
   *
   * A description of the error that occurred.
   */
  msg: string;
  /**
   * Input
   *
   * The input that caused the error.
   */
  input?: unknown;
  /**
   * Ctx
   *
   * Additional context about the error.
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Staff
   */
  is_staff?: boolean;
  /**
   * Id
   */
  id: string;
};

/**
 * UserProfileResponse
 */
export type UserProfileResponse = {
  /**
   * First Name
   */
  first_name: string | null;
  /**
   * Last Name
   */
  last_name: string | null;
  /**
   * Job Title
   */
  job_title: string | null;
  /**
   * User Role
   */
  user_role: string | null;
  /**
   * Marketing Consent
   */
  marketing_consent: boolean | null;
};

/**
 * StyleGuideSummaryResponse
 *
 * Style guide summary, as returned by ``GET /style-agent/style-guides``.
 */
export type StyleGuideSummaryResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Is Default
   */
  is_default: boolean;
  /**
   * Enabled
   */
  enabled: boolean;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Language
   */
  language?: string | null;
  /**
   * Language Name
   */
  language_name?: string | null;
  /**
   * Language Variant
   */
  language_variant?: string | null;
  /**
   * Language Variant Name
   */
  language_variant_name?: string | null;
};

/**
 * CreatorResponse
 */
export type CreatorResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
};

/**
 * PaginatedDomainsResponse
 */
export type PaginatedDomainsResponse = {
  /**
   * Domains
   */
  domains: Array<DomainResponse>;
  /**
   * Total Count
   */
  total_count: number;
  /**
   * Page
   */
  page: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * DomainResponse
 */
export type DomainResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Created By
   */
  created_by?: string | null;
  /**
   * Updated By
   */
  updated_by?: string | null;
  /**
   * Term Set Count
   */
  term_set_count?: number;
};

/**
 * OrganizationResponseFull
 */
export type OrganizationResponseFull = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Token Limit
   */
  token_limit: number;
  /**
   * Tokens Used
   */
  tokens_used: number;
  /**
   * Tier
   */
  tier: string;
  /**
   * Style Guide Limit
   */
  style_guide_limit: number;
  /**
   * Term Limit
   */
  term_limit: number;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Created Date
   */
  created_date: string;
  /**
   * Expiration
   */
  expiration: string | null;
  /**
   * Domain
   */
  domain: string;
  created_by: CreatorResponse | null;
  /**
   * Style Guides
   */
  style_guides?: number;
  /**
   * Term Sets
   */
  term_sets?: number;
  /**
   * Country
   */
  country: string | null;
  /**
   * Is Internal
   */
  is_internal: boolean;
  /**
   * Is Acrolinx Classic
   */
  is_acrolinx_classic: boolean;
  style_agent?: StyleAgentMode;
  /**
   * Style Agent Numeric Scoring
   */
  style_agent_numeric_scoring?: boolean;
  /**
   * Trial
   */
  readonly trial: boolean;
  /**
   * Tokens
   */
  readonly tokens: number;
};

/**
 * OrganizationConfigResponse
 *
 * Org-level configuration slice that drives client-side behaviour.
 *
 * Returned by ``GET /account/config`` for both JWT and API-key auth. The
 * organization is identified by the auth credential — no request-side org
 * id is needed (the API key already carries one). This intentionally omits
 * user_profile / user fields that don't make sense for API-key callers.
 */
export type OrganizationConfigResponse = {
  /**
   * Is Acrolinx Classic
   */
  is_acrolinx_classic: boolean;
  style_agent: StyleAgentMode;
  /**
   * Style Agent Numeric Scoring
   */
  style_agent_numeric_scoring: boolean;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * Detail
   *
   * A description of the error that occurred.
   */
  detail: string;
  /**
   * Status
   *
   * The HTTP status code generated by the server for this issue
   */
  status: number;
  /**
   * Request Id
   *
   * A unique ID associated with the HTTP request.
   */
  request_id: string;
};

/**
 * DomainUpdateRequest
 */
export type DomainUpdateRequest = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * DomainCreateRequest
 */
export type DomainCreateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * CategoryListResult
 *
 * Result of listing all available categories.
 */
export type CategoryListResult = {
  /**
   * Categories
   *
   * All defined categories
   */
  categories: Array<CategoryDefinition>;
  /**
   * Total
   *
   * Total number of categories
   */
  total: number;
};

/**
 * CategoryDefinition
 *
 * A single agent category for API responses.
 */
export type CategoryDefinition = {
  /**
   * Id
   *
   * Stable category ID (e.g. 'cat_r2FOEuqy06OR')
   */
  id: string;
  /**
   * Name
   *
   * Human-readable display name
   */
  name: string;
  /**
   * Description
   *
   * What this category covers
   */
  description: string;
};

/**
 * AgentUIMetadata
 *
 * UI presentation metadata for an agent.
 */
export type AgentUiMetadata = {
  /**
   * Title
   *
   * Display name override
   */
  title?: string | null;
  /**
   * Description
   *
   * Description override for UI
   */
  description?: string | null;
  /**
   * Icon
   *
   * Lucide icon key (e.g. 'spell-check')
   */
  icon?: string;
};

/**
 * AgentRunResponse
 *
 * Response from agent run.
 */
export type AgentRunResponse = {
  /**
   * Workflow Id
   *
   * Workflow ID for tracking
   */
  workflow_id: string;
  /**
   * Request Id
   *
   * Request tracking ID
   */
  request_id?: string | null;
  /**
   * Workflow status
   */
  status: HeliosSharedCortexModelsResponseWorkflowStatus;
  /**
   * Document Ref
   *
   * Caller-provided document identifier.
   */
  document_ref?: string | null;
  /**
   * Result
   *
   * Execution result (if completed)
   */
  result?: {
    [key: string]: unknown;
  } | null;
  /**
   * Started At
   *
   * Workflow start time
   */
  started_at: string;
  /**
   * Completed At
   *
   * Workflow completion time
   */
  completed_at?: string | null;
  /**
   * Duration Seconds
   *
   * Execution duration
   */
  duration_seconds?: number | null;
};

/**
 * AgentRunRequest
 *
 * Request to run an agent.
 */
export type AgentRunRequest = {
  /**
   * Text
   *
   * Document text to analyze.
   */
  text: string;
  /**
   * Agents
   *
   * Agent IDs to execute. Resolved to agent names server-side.
   */
  agents?: Array<string> | null;
  /**
   * Domain Ids
   *
   * Terminology domain IDs.
   */
  domain_ids?: Array<string> | null;
  /**
   * Document Ref
   *
   * Caller-provided document identifier for tracking across scans.
   */
  document_ref?: string | null;
  /**
   * Url
   *
   * Document URL.
   */
  url?: string | null;
  /**
   * Document Name
   *
   * Document name or title.
   */
  document_name?: string | null;
  /**
   * Style Guide Id
   *
   * Style guide ID to check the document against. ``target_id`` is a deprecated alias for this field; send exactly one of the two names.
   */
  style_guide_id?: string | null;
  /**
   * Content Profile Id
   *
   * Language-service content profile ID for style checking.
   */
  content_profile_id?: string | null;
  /**
   * Goal
   *
   * Document goal for agent recommendation.
   */
  goal?: string | null;
  /**
   * Persona Id
   *
   * Agent configuration UUID for persona selection. Used by: persona.
   */
  persona_id?: string | null;
  /**
   * Voice Profile Id
   *
   * Agent configuration UUID for brand voice profile selection. Used by: brand_voice.
   */
  voice_profile_id?: string | null;
  /**
   * Webhook Url
   *
   * Optional webhook URL for async result delivery.
   */
  webhook_url?: string | null;
};

/**
 * AgentMetadata
 *
 * Metadata about a registered agent.
 */
export type AgentMetadata = {
  /**
   * Id
   *
   * Stable agent ID (ag_<nanoid>) used for API routing
   */
  id: string;
  /**
   * Description
   *
   * Agent description
   */
  description?: string | null;
  /**
   * Labs
   *
   * Whether this agent is in labs
   */
  labs?: boolean;
  /**
   * Input Schema
   *
   * Input JSON schema
   */
  input_schema?: {
    [key: string]: unknown;
  } | null;
  /**
   * Name
   *
   * Agent name
   */
  name: string;
  /**
   * Output Schema
   *
   * Output JSON schema
   */
  output_schema?: {
    [key: string]: unknown;
  } | null;
  /**
   * Categories
   *
   * Category IDs for discovery and filtering
   */
  categories?: Array<string>;
  /**
   * UI metadata
   */
  ui?: AgentUiMetadata;
};

/**
 * ActivityEventRequest
 *
 * Request body for tracking a user action on an agent issue.
 *
 * workflow_id and request_id are promoted to top-level fields on the
 * ActivityEvent; the remaining fields are serialized into event_data.
 */
export type ActivityEventRequest = {
  /**
   * Workflow Id
   *
   * Workflow ID of the check that produced the issue (null for pre-scan actions)
   */
  workflow_id?: string | null;
  /**
   * Request Id
   *
   * Request ID of the check that produced the issue (empty for pre-scan actions; handler falls back to API request ID)
   */
  request_id?: string;
  /**
   * Session Id
   *
   * Client-generated UUID per sidepanel lifecycle
   */
  session_id: string;
  /**
   * Action
   *
   * Action taken (e.g., 'APPLY_CHANGE', 'dismiss', 'mark-resolve')
   */
  action: string;
  /**
   * Issue Id
   *
   * Backend-generated issue ID (iss_xxx)
   */
  issue_id?: string | null;
  /**
   * Agent Id
   *
   * Stable agent ID (ag_<nanoid>)
   */
  agent_id?: string | null;
  /**
   * Agent Name
   *
   * Agent that produced the issue
   */
  agent_name?: string | null;
  /**
   * Action Source
   *
   * Where the action was triggered (e.g., 'issue_panel', 'tooltip', 'work', 'goal', 'plan')
   */
  action_source: string;
  /**
   * Document Ref
   *
   * Normalized document URL
   */
  document_ref?: string | null;
  /**
   * Mode
   *
   * Workflow mode: 'guided' or 'manual'
   */
  mode?: string | null;
  /**
   * Goal Id
   *
   * Stable goal identifier (e.g., 'brand-consistency')
   */
  goal_id?: string | null;
  /**
   * Goal Agent Names
   *
   * Agent slugs associated with the selected goal
   */
  goal_agent_names?: Array<string> | null;
  /**
   * Goal Agent Ids
   *
   * Stable agent IDs (ag_<nanoid>) for the selected goal
   */
  goal_agent_ids?: Array<string> | null;
  /**
   * Status
   *
   * Outcome of the action: 'success' or 'failed'
   */
  status?: string | null;
  /**
   * Error Code
   *
   * Error description if the action failed
   */
  error_code?: string | null;
  /**
   * Timestamp
   *
   * Timestamp when the action was initiated
   */
  timestamp?: string | null;
};

/**
 * AccountResponse
 */
export type AccountResponse = {
  organization: OrganizationResponseFull;
  user_profile: UserProfileResponse;
  user?: UserRead | null;
};

/**
 * OrganizationResponseFull
 */
export type OrganizationResponseFullWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Token Limit
   */
  token_limit: number;
  /**
   * Tokens Used
   */
  tokens_used: number;
  /**
   * Tier
   */
  tier: string;
  /**
   * Style Guide Limit
   */
  style_guide_limit: number;
  /**
   * Term Limit
   */
  term_limit: number;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Created Date
   */
  created_date: string;
  /**
   * Expiration
   */
  expiration: string | null;
  /**
   * Domain
   */
  domain: string;
  created_by: CreatorResponse | null;
  /**
   * Style Guides
   */
  style_guides?: number;
  /**
   * Term Sets
   */
  term_sets?: number;
  /**
   * Country
   */
  country: string | null;
  /**
   * Is Internal
   */
  is_internal: boolean;
  /**
   * Is Acrolinx Classic
   */
  is_acrolinx_classic: boolean;
  style_agent?: StyleAgentMode;
  /**
   * Style Agent Numeric Scoring
   */
  style_agent_numeric_scoring?: boolean;
};

/**
 * AccountResponse
 */
export type AccountResponseWritable = {
  organization: OrganizationResponseFullWritable;
  user_profile: UserProfileResponse;
  user?: UserRead | null;
};

export type TerminologyListDomainsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number (1-based)
     */
    page?: number;
    /**
     * Page Size
     *
     * Number of items per page
     */
    page_size?: number;
    /**
     * Search
     *
     * Optional name filter
     */
    search?: string | null;
  };
  url: "/v1/terminology/domains";
};

export type TerminologyListDomainsErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type TerminologyListDomainsError =
  TerminologyListDomainsErrors[keyof TerminologyListDomainsErrors];

export type TerminologyListDomainsResponses = {
  /**
   * Successful Response
   */
  200: PaginatedDomainsResponse;
};

export type TerminologyListDomainsResponse =
  TerminologyListDomainsResponses[keyof TerminologyListDomainsResponses];

export type TerminologyCreateDomainData = {
  body: DomainCreateRequest;
  path?: never;
  query?: never;
  url: "/v1/terminology/domains";
};

export type TerminologyCreateDomainErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type TerminologyCreateDomainError =
  TerminologyCreateDomainErrors[keyof TerminologyCreateDomainErrors];

export type TerminologyCreateDomainResponses = {
  /**
   * Successful Response
   */
  201: DomainResponse;
};

export type TerminologyCreateDomainResponse =
  TerminologyCreateDomainResponses[keyof TerminologyCreateDomainResponses];

export type TerminologyDeleteDomainData = {
  body?: never;
  path: {
    /**
     * Domain Id
     *
     * UUID of the domain
     */
    domain_id: string;
  };
  query?: never;
  url: "/v1/terminology/domains/{domain_id}";
};

export type TerminologyDeleteDomainErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type TerminologyDeleteDomainError =
  TerminologyDeleteDomainErrors[keyof TerminologyDeleteDomainErrors];

export type TerminologyDeleteDomainResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type TerminologyDeleteDomainResponse =
  TerminologyDeleteDomainResponses[keyof TerminologyDeleteDomainResponses];

export type TerminologyGetDomainData = {
  body?: never;
  path: {
    /**
     * Domain Id
     *
     * UUID of the domain
     */
    domain_id: string;
  };
  query?: never;
  url: "/v1/terminology/domains/{domain_id}";
};

export type TerminologyGetDomainErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type TerminologyGetDomainError =
  TerminologyGetDomainErrors[keyof TerminologyGetDomainErrors];

export type TerminologyGetDomainResponses = {
  /**
   * Successful Response
   */
  200: DomainResponse;
};

export type TerminologyGetDomainResponse =
  TerminologyGetDomainResponses[keyof TerminologyGetDomainResponses];

export type TerminologyUpdateDomainData = {
  body: DomainUpdateRequest;
  path: {
    /**
     * Domain Id
     *
     * UUID of the domain
     */
    domain_id: string;
  };
  query?: never;
  url: "/v1/terminology/domains/{domain_id}";
};

export type TerminologyUpdateDomainErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type TerminologyUpdateDomainError =
  TerminologyUpdateDomainErrors[keyof TerminologyUpdateDomainErrors];

export type TerminologyUpdateDomainResponses = {
  /**
   * Successful Response
   */
  200: DomainResponse;
};

export type TerminologyUpdateDomainResponse =
  TerminologyUpdateDomainResponses[keyof TerminologyUpdateDomainResponses];

export type StyleAgentListStyleGuidesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/style-agent/style-guides";
};

export type StyleAgentListStyleGuidesErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type StyleAgentListStyleGuidesError =
  StyleAgentListStyleGuidesErrors[keyof StyleAgentListStyleGuidesErrors];

export type StyleAgentListStyleGuidesResponses = {
  /**
   * Response Style Agent-List Style Guides
   *
   * Successful Response
   */
  200: Array<StyleGuideSummaryResponse>;
};

export type StyleAgentListStyleGuidesResponse =
  StyleAgentListStyleGuidesResponses[keyof StyleAgentListStyleGuidesResponses];

export type AccountGetAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/account";
};

export type AccountGetAccountErrors = {
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type AccountGetAccountError = AccountGetAccountErrors[keyof AccountGetAccountErrors];

export type AccountGetAccountResponses = {
  /**
   * Successful Response
   */
  200: AccountResponse;
};

export type AccountGetAccountResponse =
  AccountGetAccountResponses[keyof AccountGetAccountResponses];

export type AuthenticationGetUserOrganizationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/organizations";
};

export type AuthenticationGetUserOrganizationsErrors = {
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type AuthenticationGetUserOrganizationsError =
  AuthenticationGetUserOrganizationsErrors[keyof AuthenticationGetUserOrganizationsErrors];

export type AuthenticationGetUserOrganizationsResponses = {
  /**
   * Response Authentication-Get User Organizations
   *
   * Successful Response
   */
  200: Array<HeliosOneApiModulesAuthMainOrganization>;
};

export type AuthenticationGetUserOrganizationsResponse =
  AuthenticationGetUserOrganizationsResponses[keyof AuthenticationGetUserOrganizationsResponses];

export type CortexActivityEventsTrackActivityEventData = {
  body: ActivityEventRequest;
  path?: never;
  query?: never;
  url: "/agents/activity-events";
};

export type CortexActivityEventsTrackActivityEventErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CortexActivityEventsTrackActivityEventError =
  CortexActivityEventsTrackActivityEventErrors[keyof CortexActivityEventsTrackActivityEventErrors];

export type CortexActivityEventsTrackActivityEventResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type CortexActivityEventsTrackActivityEventResponse =
  CortexActivityEventsTrackActivityEventResponses[keyof CortexActivityEventsTrackActivityEventResponses];

export type CortexWorkflowsListWorkflowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     *
     * Filter by workflow status
     */
    status?: "running" | "completed" | "failed" | "cancelled" | "timed_out" | "terminated" | null;
    /**
     * Agent Id
     *
     * Filter by agent ID
     */
    agent_id?: string | null;
    /**
     * Created After
     *
     * Only return workflows created after this timestamp (ISO 8601)
     */
    created_after?: string | null;
    /**
     * Limit
     *
     * Maximum number of results per page
     */
    limit?: number;
    /**
     * Cursor
     *
     * Opaque cursor from a previous response to fetch the next page
     */
    cursor?: string | null;
  };
  url: "/agents/workflows";
};

export type CortexWorkflowsListWorkflowsErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Agent not found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  /**
   * Failed to list workflows
   */
  502: ErrorResponse;
};

export type CortexWorkflowsListWorkflowsError =
  CortexWorkflowsListWorkflowsErrors[keyof CortexWorkflowsListWorkflowsErrors];

export type CortexWorkflowsListWorkflowsResponses = {
  /**
   * Successful Response
   */
  200: WorkflowListResponse;
};

export type CortexWorkflowsListWorkflowsResponse =
  CortexWorkflowsListWorkflowsResponses[keyof CortexWorkflowsListWorkflowsResponses];

export type CortexWorkflowsCancelWorkflowData = {
  body?: never;
  path: {
    /**
     * Workflow Id
     */
    workflow_id: string;
  };
  query?: never;
  url: "/agents/workflows/{workflow_id}";
};

export type CortexWorkflowsCancelWorkflowErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Workflow not found
   */
  404: ErrorResponse;
  /**
   * Workflow cannot be cancelled
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Failed to cancel workflow
   */
  500: ErrorResponse;
};

export type CortexWorkflowsCancelWorkflowError =
  CortexWorkflowsCancelWorkflowErrors[keyof CortexWorkflowsCancelWorkflowErrors];

export type CortexWorkflowsCancelWorkflowResponses = {
  /**
   * Successful Response
   */
  200: WorkflowCancelResponse;
};

export type CortexWorkflowsCancelWorkflowResponse =
  CortexWorkflowsCancelWorkflowResponses[keyof CortexWorkflowsCancelWorkflowResponses];

export type CortexWorkflowsGetWorkflowStatusData = {
  body?: never;
  path: {
    /**
     * Workflow Id
     */
    workflow_id: string;
  };
  query?: never;
  url: "/agents/workflows/{workflow_id}";
};

export type CortexWorkflowsGetWorkflowStatusErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Workflow not found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Failed to retrieve workflow status
   */
  500: ErrorResponse;
};

export type CortexWorkflowsGetWorkflowStatusError =
  CortexWorkflowsGetWorkflowStatusErrors[keyof CortexWorkflowsGetWorkflowStatusErrors];

export type CortexWorkflowsGetWorkflowStatusResponses = {
  /**
   * Successful Response
   */
  200: WorkflowStatusResponse;
};

export type CortexWorkflowsGetWorkflowStatusResponse =
  CortexWorkflowsGetWorkflowStatusResponses[keyof CortexWorkflowsGetWorkflowStatusResponses];

export type CortexWorkflowsStreamWorkflowEventsData = {
  body?: never;
  path: {
    /**
     * Workflow Id
     */
    workflow_id: string;
  };
  query?: never;
  url: "/agents/workflows/{workflow_id}/stream";
};

export type CortexWorkflowsStreamWorkflowEventsErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Workflow not found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Failed to retrieve workflow status
   */
  500: ErrorResponse;
  /**
   * Streaming not enabled
   */
  503: ErrorResponse;
};

export type CortexWorkflowsStreamWorkflowEventsError =
  CortexWorkflowsStreamWorkflowEventsErrors[keyof CortexWorkflowsStreamWorkflowEventsErrors];

export type CortexWorkflowsStreamWorkflowEventsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CortexAgentsListCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/categories";
};

export type CortexAgentsListCategoriesErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CortexAgentsListCategoriesError =
  CortexAgentsListCategoriesErrors[keyof CortexAgentsListCategoriesErrors];

export type CortexAgentsListCategoriesResponses = {
  /**
   * Successful Response
   */
  200: CategoryListResult;
};

export type CortexAgentsListCategoriesResponse =
  CortexAgentsListCategoriesResponses[keyof CortexAgentsListCategoriesResponses];

export type CortexAgentsGetAgentData = {
  body?: never;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/agents/{agent_id}";
};

export type CortexAgentsGetAgentErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CortexAgentsGetAgentError =
  CortexAgentsGetAgentErrors[keyof CortexAgentsGetAgentErrors];

export type CortexAgentsGetAgentResponses = {
  /**
   * Successful Response
   */
  200: AgentMetadata;
};

export type CortexAgentsGetAgentResponse =
  CortexAgentsGetAgentResponses[keyof CortexAgentsGetAgentResponses];

export type CortexAgentsRunAgentData = {
  body: AgentRunRequest;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: {
    /**
     * Wait
     */
    wait?: boolean;
  };
  url: "/agents/{agent_id}/run";
};

export type CortexAgentsRunAgentErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Invalid input for agent
   */
  422: unknown;
  /**
   * Workflow execution failed (wait=true)
   */
  500: unknown;
};

export type CortexAgentsRunAgentError =
  CortexAgentsRunAgentErrors[keyof CortexAgentsRunAgentErrors];

export type CortexAgentsRunAgentResponses = {
  /**
   * Successful Response
   */
  200: AgentRunResponse;
  /**
   * Completed (wait=true)
   */
  201: AgentRunResponse;
  /**
   * Accepted (wait=false)
   */
  202: AgentRunResponse;
};

export type CortexAgentsRunAgentResponse =
  CortexAgentsRunAgentResponses[keyof CortexAgentsRunAgentResponses];

export type AccountGetAccountConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/account/config";
};

export type AccountGetAccountConfigErrors = {
  /**
   * Authentication failed or no valid API key provided.
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ValidationErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type AccountGetAccountConfigError =
  AccountGetAccountConfigErrors[keyof AccountGetAccountConfigErrors];

export type AccountGetAccountConfigResponses = {
  /**
   * Successful Response
   */
  200: OrganizationConfigResponse;
};

export type AccountGetAccountConfigResponse =
  AccountGetAccountConfigResponses[keyof AccountGetAccountConfigResponses];
