import CustomGlobalStyles from "@/components/GlobalStyles/GlobalStyles";
import Providers from "@/components/Providers/Providers";
import "@/styles/global.scss";
import { ReduxProviders } from "./redux/provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {process.env.NEXT_PUBLIC_USERSNAP_API_KEY &&
          process.env.NEXT_PUBLIC_USERSNAP_ENABLE == "true" && (
            <script
              dangerouslySetInnerHTML={{
                __html: `
                  window.onUsersnapLoad = function(api) {
                    api.init();
                  }
                  var script = document.createElement('script');
                  script.async = 1;
                  script.src = 'https://widget.usersnap.com/global/load/${process.env.NEXT_PUBLIC_USERSNAP_API_KEY}?onload=onUsersnapLoad';
                  document.getElementsByTagName('head')[0].appendChild(script);`,
              }}
            />
          )}
        {process.env.NEXT_PUBLIC_GTM_ID &&
          process.env.NEXT_PUBLIC_ENABLE_GTM == "true" && (
            <script
              dangerouslySetInnerHTML={{
                __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),
                dl=l!='dataLayer'?'&l='+l:'';j.async=true;
                j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${process.env.NEXT_PUBLIC_GTM_ID}');`,
              }}
            ></script>
          )}
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>

      <body>
        {
          process.env.NEXT_PUBLIC_GTM_ID &&
            process.env.NEXT_PUBLIC_ENABLE_GTM == "true" && (
              /* <!-- Google Tag Manager (noscript) --> */
              <noscript
                dangerouslySetInnerHTML={{
                  __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=${process.env.NEXT_PUBLIC_GTM_ID?.replaceAll(
                    '"',
                    ""
                  )}"
                 height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
                }}
              />
            )
          /* <!-- End Google Tag Manager (noscript) --> */
        }

        <ReduxProviders>
          <CustomGlobalStyles />
          <Providers>{children}</Providers>
        </ReduxProviders>
      </body>
    </html>
  );
}
