name: 'App Review Check'

on:
  pull_request:
    # types:
    #   - opened
    #   - edited
    #   - synchronize
    # branches:
    #   - 'main'
    #   - 'feat/gha-code-review'

permissions:
  pull-requests: write

jobs:
  main:
    name: App Review Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/workflows/app-review-script.js')
            await script({github, context, core})
