---
name: 'Automated Code Suggestions'

"on":
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      target_app:
        description: 'Specific app to analyze (optional, leave empty for all apps)'
        required: false
        type: string

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  analyze-and-suggest:
    name: Analyze Apps and Create Code Suggestions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Need full history to properly analyze changes
          fetch-depth: 0
          # Use a token that can create PRs
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Compile TypeScript
        run: npx tsc --project .github/workflows/tsconfig.json
      - uses: actions/github-script@v7
        with:
          script: |
            const { analyzeSuggestAndCreate } = require(
              './.github/workflows/dist/code-suggestions'
            );
            const { chdir, cwd } = require('node:process');
            chdir(cwd());
            await analyzeSuggestAndCreate({
              github,
              ctx: context,
              ghCore: core,
              targetApp: '${{ github.event.inputs.target_app || '' }}'
            });